import spacy
from string import punctuation

nlp=spacy.load('en_core_web_sm')
stopwords=nlp.Defaults.stop_words

def preprocess(text):
    text = text.lower()
    doc=nlp(text)
    tokens=[token for token in doc]
    for token in tokens:
        if token in stopwords or str(token) in punctuation:
            tokens.remove(token)
    tokens = [token.lemma_ for token in tokens]
    preprocessed_text = ' '.join(tokens)
    return preprocessed_text

def return_languages():
    languages={'Hindi': 'hi-IN',
        'Bengali': 'bn-IN',
        'Telugu': 'te-IN',
        'Marathi': 'mr-IN',
        'Tamil': 'ta-IN',
        'Urdu': 'ur-IN',
        'Gujarati': 'gu-IN',
        'Malayalam': 'ml-IN',
        'Kannada': 'kn-IN',
        'Odia': 'or-IN',
        'Punjabi': 'pa-IN',
        'Assamese': 'as-IN',

        'Afrikaans': 'af-ZA',
        'Albanian': 'sq-AL',
        'Amharic': 'am-ET',
        'Arabic': 'ar-SA',
        'Armenian': 'hy-AM',
        'Azerbaijani': 'az-AZ',
        'Basque': 'eu-ES',
        'Belarusian': 'be-BY',
        'Bosnian': 'bs-BA',
        'Bulgarian': 'bg-BG',
        'Catalan': 'ca-ES',
        'Cebuano': 'ceb-PH',
        'Chinese (Simplified)': 'zh-CN',
        'Chinese (Traditional)': 'zh-TW',
        'Corsican': 'co-FR',
        'Croatian': 'hr-HR',
        'Czech': 'cs-CZ',
        'Danish': 'da-DK',
        'Dutch': 'nl-NL',
        'English': 'en-US',
        'Esperanto': 'eo-EO',
        'Estonian': 'et-EE',
        'Finnish': 'fi-FI',
        'French': 'fr-FR',
        'Frisian': 'fy-NL',
        'Galician': 'gl-ES',
        'Georgian': 'ka-GE',
        'German': 'de-DE',
        'Greek': 'el-GR',
        'Haitian Creole': 'ht-HT',
        'Hausa': 'ha-NG',
        'Hawaiian': 'haw-US',
        'Hebrew': 'he-IL',
        'Hmong': 'hmn-CN',
        'Hungarian': 'hu-HU',
        'Icelandic': 'is-IS',
        'Igbo': 'ig-NG',
        'Indonesian': 'id-ID',
        'Irish': 'ga-IE',
        'Italian': 'it-IT',
        'Japanese': 'ja-JP',
        'Javanese': 'jv-ID',
        'Hebrew': 'he-IL',
        'Kazakh': 'kk-KZ',
        'Khmer': 'km-KH',
        'Korean': 'ko-KR',
        'Kurdish': 'ku-TR',
        'Kyrgyz': 'ky-KG',
        'Lao': 'lo-LA',
        'Latin': 'la-VA',
        'Latvian': 'lv-LV',
        'Lithuanian': 'lt-LT',
        'Luxembourgish': 'lb-LU',
        'Macedonian': 'mk-MK',
        'Malagasy': 'mg-MG',
        'Malay': 'ms-MY',
        'Malayalam': 'ml-IN',
        'Maltese': 'mt-MT',
        'Maori': 'mi-NZ',
        'Mongolian': 'mn-MN',
        'Burmese': 'my-MM',
        'Nepali': 'ne-NP',
        'Norwegian': 'no-NO',
        'Nyanja (Chichewa)': 'ny-MW',
        'Pashto': 'ps-AF',
        'Persian': 'fa-IR',
        'Polish': 'pl-PL',
        'Portuguese': 'pt-PT',
        'Romanian': 'ro-RO',
        'Russian': 'ru-RU',
        'Quechua': 'qu-PE',
        'Samoan': 'sm-WS',
        'Sanskrit': 'sa-IN',
        'Scots Gaelic': 'gd-GB',
        'Serbian': 'sr-RS',
        'Sesotho': 'st-ZA',
        'Shona': 'sn-ZW',
        'Sindhi': 'sd-PK',
        'Sinhala (Sinhalese)': 'si-LK',
        'Slovak': 'sk-SK',
        'Slovenian': 'sl-SI',
        'Somali': 'so-SO',
        'Spanish': 'es-ES',
        'Sundanese': 'su-ID',
        'Swahili': 'sw-KE',
        'Swedish': 'sv-SE',
        'Tagalog (Filipino)': 'tl-PH',
        'Tajik': 'tg-TJ',
        'Thai': 'th-TH',
        'Turkish': 'tr-TR',
        'Ukrainian': 'uk-UA',
        'Urdu': 'ur-PK',
        'Uzbek': 'uz-UZ',
        'Vietnamese': 'vi-VN',
        'Welsh': 'cy-GB',
        'Xhosa': 'xh-ZA',
        'Yiddish': 'yi-DE',
        'Yoruba': 'yo-NG',
        'Zulu': 'zu-ZA'
        }
    
    return languages